# Stage 1
FROM node:12-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY front-game/package.json /app
RUN npm install
COPY front-game/. /app
RUN npm run build --prod
# Stage 2
FROM nginx:1.17.1-alpine
COPY --from=build-step /app/dist/front-game /etc/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf